[versions]
java = "1.8.0"
version-plugin-agp = "7.4.1"

[libraries]

[plugins]
androidApp = { id = "com.android.application", version.ref = "version-plugin-agp" }
androidLibrary = { id = "com.android.library", version.ref = "version-plugin-agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "java" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "java" }